export const apiConfig = {
  backend: 'supabase',
};

export const endpoints = {
  auth: {
    signIn: 'supabase.auth.signInWithPassword',
    signUp: 'supabase.auth.signUpWithPassword',
    google: 'supabase.auth.signInWithGoogle',
  },
  content: {
    courses: 'courses',
    batches: 'batches',
  },
  tests: {
    list: 'test_catalog',
    available: 'list_available_tests',
    questions: 'test_questions',
    availableQuestions: 'list_test_questions',
    leaderboard: 'get_leaderboard',
    studentInsights: 'get_student_insights',
    review: 'review_answers',
    existingAttempt: 'get_existing_attempt_for_test',
    submit: 'submit_test_attempt',
    enrollmentQuery: 'submit_enrollment_query',
    scholarshipRegistration: 'upsert_scholarship_registration',
    enquiry: 'submit_general_enquiry',
    logViolation: 'log-violation',
  },
  admin: {
    users: 'admin_user_directory',
    results: 'test_attempt_summaries',
    enrollmentQueries: 'admin_enrollment_queries',
    scholarshipRegistrations: 'admin_scholarship_registrations',
    enquiries: 'admin_general_enquiries',
    analytics: 'get_admin_analytics',
    questionAnalytics: 'question_analytics',
    testAnalytics: 'test_analytics',
    studentAnalytics: 'student_analytics',
    autoSubmitEvents: 'admin_auto_submit_events',
    violationAnalytics: 'admin_violation_summary',
    createTest: 'create_test_with_questions',
    createBatch: 'create_batch',
    updateTest: 'update_test_details',
    setTestStarted: 'set_test_started',
    pdfImport: 'pdf-to-questions',
    assignBatch: 'assign_batch_and_role',
    approveAdmin: 'approve_admin_user',
    deleteTest: 'delete_test',
    deleteBatch: 'delete_batch',
    wipeLeaderboard: 'wipe_leaderboard',
    deleteAttempt: 'delete_test_attempt',
    deleteEnrollmentQuery: 'delete_enrollment_query',
    deleteScholarshipRegistration: 'delete_scholarship_registration',
    deleteGeneralEnquiry: 'delete_general_enquiry',
    deleteQuestionSet: 'delete_question_set',
    insertActivityLogs: 'insert_activity_logs',
    fetchActivityLogs: 'fetch_activity_logs',
  },
};
