import json, base64, os, sys

sys.stdout.reconfigure(encoding='utf-8')

img_dir = r'D:\Downloads\miitjee-mobile\question paper\extracted'
json_path = os.path.join(img_dir, 'questions.json')

with open(json_path, 'r', encoding='utf-8') as f:
    questions = json.load(f)

# Load images to base64 data URIs
img_b64 = {}
for i in range(1, 9):
    fn = f"image{i}.png"
    fp = os.path.join(img_dir, fn)
    if os.path.exists(fp):
        with open(fp, 'rb') as img_f:
            b64_str = base64.b64encode(img_f.read()).decode('utf-8')
            img_b64[fn] = f"data:image/png;base64,{b64_str}"

print(f"Loaded {len(img_b64)} images.")

test_id = "a0000000-0000-0000-0000-000000000075"

# Clean up questions
cleaned_questions = []
for q in questions:
    q_num = q['q_num']
    sub = q['subject']
    sec = q['section']
    q_type = 'mcq' if q['type'] == 'MCQ' else 'integer'
    prompt = q['text'].strip()
    
    # Remove stray "undefined" if present in prompt
    prompt = '\n'.join([line for line in prompt.split('\n') if line.strip() != 'undefined'])
    
    # Options array
    opts = []
    if q_type == 'mcq':
        for k in ['A', 'B', 'C', 'D']:
            opts.append(q['options'].get(k, ''))
            
    corr_ans = str(q['correct_answer']).strip() if q['correct_answer'] is not None else ''
    int_ans = None
    if q_type == 'integer':
        try:
            int_ans = int(float(corr_ans))
        except:
            int_ans = None
            
    # Image url
    img_url = None
    if q['images']:
        first_img = q['images'][0]
        if first_img in img_b64:
            img_url = img_b64[first_img]
            
    cleaned_questions.append({
        'position': q_num,
        'subject_label': sub,
        'question_type': q_type,
        'prompt': prompt,
        'options': opts,
        'correct_answer': corr_ans,
        'integer_answer': int_ans,
        'explanation': f"Correct answer is {corr_ans}.",
        'image_url': img_url
    })

print(f"Cleaned {len(cleaned_questions)} questions.")

# Generate SQL migration
sql_lines = [
    "-- Migration: Navigator Batch MIITJEE Question Paper & Open-for-All Weekly Test Submission Fix",
    "-- Date: 2026-09-06",
    "",
    "-- 1. Update submit_test_attempt function to allow Open for All weekly tests without batch locking",
    "DROP FUNCTION IF EXISTS public.submit_test_attempt(UUID, JSONB);",
    "DROP FUNCTION IF EXISTS public.submit_test_attempt(UUID, JSONB, TEXT);",
    "",
    "CREATE OR REPLACE FUNCTION public.submit_test_attempt(",
    "  p_test_id UUID,",
    "  p_answers JSONB,",
    "  p_student_name TEXT DEFAULT NULL",
    ")",
    "RETURNS JSONB",
    "LANGUAGE plpgsql",
    "SECURITY DEFINER",
    "SET search_path = public",
    "AS $$",
    "DECLARE",
    "  v_uid UUID := auth.uid();",
    "  v_total_questions INTEGER := 0;",
    "  v_correct_answers INTEGER := 0;",
    "  v_wrong_answers INTEGER := 0;",
    "  v_unattempted INTEGER := 0;",
    "  v_score INTEGER := 0;",
    "  v_attempt public.test_attempts;",
    "  v_user JSONB;",
    "  v_result JSONB;",
    "  v_leaderboard JSONB;",
    "  v_overall_leaderboard JSONB;",
    "  v_profile public.profiles;",
    "  v_test RECORD;",
    "  v_leaderboard_batch_id TEXT;",
    "  v_now TIMESTAMPTZ := timezone('utc', now());",
    "  v_correct_marks NUMERIC := 4;",
    "  v_wrong_marks NUMERIC := -1;",
    "  v_unattempted_marks NUMERIC := 0;",
    "  v_final_student_name TEXT;",
    "BEGIN",
    "  IF v_uid IS NULL THEN",
    "    RAISE EXCEPTION 'Authentication required';",
    "  END IF;",
    "",
    "  IF EXISTS (",
    "    SELECT 1",
    "    FROM public.test_attempts",
    "    WHERE test_id = p_test_id",
    "      AND user_id = v_uid",
    "  ) THEN",
    "    RAISE EXCEPTION 'You have already given this test.';",
    "  END IF;",
    "",
    "  SELECT *",
    "  INTO v_profile",
    "  FROM public.profiles",
    "  WHERE id = v_uid;",
    "",
    "  SELECT *",
    "  INTO v_test",
    "  FROM public.tests",
    "  WHERE id = p_test_id",
    "    AND is_published = TRUE",
    "    AND deleted_at IS NULL;",
    "",
    "  IF v_test.id IS NULL THEN",
    "    RAISE EXCEPTION 'Test not found';",
    "  END IF;",
    "",
    "  IF NOT public.is_admin()",
    "    AND NOT (",
    "      COALESCE(v_test.is_started, FALSE)",
    "      OR COALESCE(v_test.started_at, v_test.scheduled_at, v_now) <= v_now",
    "    ) THEN",
    "    RAISE EXCEPTION 'This test is locked until an admin starts it.';",
    "  END IF;",
    "",
    "  -- Allow weekly tests when open for all or no batch assigned",
    "  IF v_test.type = 'weekly' AND NOT public.is_admin() THEN",
    "    IF NOT (",
    "      COALESCE(v_test.is_open_for_all, FALSE) = TRUE",
    "      OR v_test.batch_id IS NULL",
    "      OR v_test.batch_id = 'ALL'",
    "      OR LOWER(v_test.batch_id) = 'all batches'",
    "      OR (",
    "        v_profile.batch_id IS NOT NULL",
    "        AND v_profile.batch_id = v_test.batch_id",
    "      )",
    "    ) THEN",
    "      RAISE EXCEPTION 'Weekly tests are only for students of the matching batch';",
    "    END IF;",
    "  END IF;",
    "",
    "  IF v_test.type = 'scholarship' THEN",
    "    IF NOT public.is_admin() AND v_profile.role = 'miitjee_student' THEN",
    "      RAISE EXCEPTION 'MIITJEE students cannot attempt scholarship tests';",
    "    END IF;",
    "",
    "    IF NOT EXISTS (",
    "      SELECT 1",
    "      FROM public.scholarship_registrations",
    "      WHERE test_id = p_test_id",
    "        AND user_id = v_uid",
    "    ) THEN",
    "      RAISE EXCEPTION 'Scholarship registration is required before starting the test';",
    "    END IF;",
    "  END IF;",
    "",
    "  v_final_student_name := COALESCE(NULLIF(TRIM(p_student_name), ''), v_profile.full_name, 'Student');",
    "",
    "  -- Load test marking scheme safely if specified",
    "  v_correct_marks := COALESCE((to_jsonb(v_test) ->> 'correct_marks')::NUMERIC, 4);",
    "  v_wrong_marks := COALESCE((to_jsonb(v_test) ->> 'wrong_marks')::NUMERIC, -1);",
    "  v_unattempted_marks := COALESCE((to_jsonb(v_test) ->> 'unattempted_marks')::NUMERIC, 0);",
    "",
    "  -- Count total questions",
    "  SELECT COUNT(*)::INT",
    "  INTO v_total_questions",
    "  FROM public.test_questions",
    "  WHERE test_id = p_test_id;",
    "",
    "  -- Count correct answers (selected answer matches correct answer or numeric value and is non-empty)",
    "  SELECT COUNT(*)::INT",
    "  INTO v_correct_answers",
    "  FROM public.test_questions q",
    "  WHERE q.test_id = p_test_id",
    "    AND NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') IS NOT NULL",
    "    AND (",
    "      LOWER(TRIM(REGEXP_REPLACE(COALESCE(p_answers ->> q.id::TEXT, ''), '^Option\\s+', '', 'i'))) = LOWER(TRIM(REGEXP_REPLACE(COALESCE(q.correct_answer, ''), '^Option\\s+', '', 'i')))",
    "      OR (",
    "        q.integer_answer IS NOT NULL",
    "        AND NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') ~ '^-?[0-9]+(\\.[0-9]+)?$'",
    "        AND (TRIM(p_answers ->> q.id::TEXT))::NUMERIC = q.integer_answer::NUMERIC",
    "      )",
    "    );",
    "",
    "  -- Count attempted wrong questions",
    "  SELECT COUNT(*)::INT",
    "  INTO v_wrong_answers",
    "  FROM public.test_questions q",
    "  WHERE q.test_id = p_test_id",
    "    AND NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') IS NOT NULL",
    "    AND NOT (",
    "      LOWER(TRIM(REGEXP_REPLACE(COALESCE(p_answers ->> q.id::TEXT, ''), '^Option\\s+', '', 'i'))) = LOWER(TRIM(REGEXP_REPLACE(COALESCE(q.correct_answer, ''), '^Option\\s+', '', 'i')))",
    "      OR (",
    "        q.integer_answer IS NOT NULL",
    "        AND NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') ~ '^-?[0-9]+(\\.[0-9]+)?$'",
    "        AND (TRIM(p_answers ->> q.id::TEXT))::NUMERIC = q.integer_answer::NUMERIC",
    "      )",
    "    );",
    "",
    "  -- Calculate unattempted count",
    "  v_unattempted := GREATEST(0, v_total_questions - v_correct_answers - v_wrong_answers);",
    "",
    "  -- Calculate score: (correct * +4) + (wrong * -1) + (unattempted * 0)",
    "  v_score := ROUND(",
    "    (v_correct_answers::NUMERIC * v_correct_marks) +",
    "    (v_wrong_answers::NUMERIC * v_wrong_marks) +",
    "    (v_unattempted::NUMERIC * v_unattempted_marks)",
    "  )::INT;",
    "",
    "  -- Insert attempt record",
    "  INSERT INTO public.test_attempts (",
    "    test_id,",
    "    user_id,",
    "    student_name,",
    "    answers,",
    "    score,",
    "    correct_answers,",
    "    wrong_answers,",
    "    unattempted,",
    "    total_questions,",
    "    percentile,",
    "    submitted_at",
    "  )",
    "  VALUES (",
    "    p_test_id,",
    "    v_uid,",
    "    v_final_student_name,",
    "    COALESCE(p_answers, '{}'::jsonb),",
    "    v_score,",
    "    v_correct_answers,",
    "    v_wrong_answers,",
    "    v_unattempted,",
    "    v_total_questions,",
    "    0,",
    "    v_now",
    "  )",
    "  RETURNING * INTO v_attempt;",
    "",
    "  -- Populate test_attempt_answers table if it exists",
    "  IF EXISTS (",
    "    SELECT 1 FROM information_schema.tables ",
    "    WHERE table_schema = 'public' AND table_name = 'test_attempt_answers'",
    "  ) THEN",
    "    BEGIN",
    "      INSERT INTO public.test_attempt_answers (",
    "        attempt_id,",
    "        question_id,",
    "        selected_answer,",
    "        correct_answer,",
    "        is_correct",
    "      )",
    "      SELECT",
    "        v_attempt.id,",
    "        q.id,",
    "        COALESCE(p_answers ->> q.id::TEXT, ''),",
    "        COALESCE(q.correct_answer, ''),",
    "        (",
    "          NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') IS NOT NULL",
    "          AND (",
    "            LOWER(TRIM(REGEXP_REPLACE(COALESCE(p_answers ->> q.id::TEXT, ''), '^Option\\s+', '', 'i'))) = LOWER(TRIM(REGEXP_REPLACE(COALESCE(q.correct_answer, ''), '^Option\\s+', '', 'i')))",
    "            OR (",
    "              q.integer_answer IS NOT NULL",
    "              AND NULLIF(TRIM(COALESCE(p_answers ->> q.id::TEXT, '')), '') ~ '^-?[0-9]+(\\.[0-9]+)?$'",
    "              AND (TRIM(p_answers ->> q.id::TEXT))::NUMERIC = q.integer_answer::NUMERIC",
    "            )",
    "          )",
    "        )",
    "      FROM public.test_questions q",
    "      WHERE q.test_id = p_test_id;",
    "    EXCEPTION WHEN OTHERS THEN",
    "      -- Ignore secondary table insert errors",
    "    END;",
    "  END IF;",
    "",
    "  -- Recalculate percentiles for this test",
    "  WITH ranked AS (",
    "    SELECT",
    "      id,",
    "      PERCENT_RANK() OVER (ORDER BY score ASC, submitted_at DESC) * 100 AS calc_percentile",
    "    FROM public.test_attempts",
    "    WHERE test_id = p_test_id",
    "  )",
    "  UPDATE public.test_attempts a",
    "  SET percentile = ROUND(r.calc_percentile::NUMERIC, 2)::DOUBLE PRECISION",
    "  FROM ranked r",
    "  WHERE a.id = r.id;",
    "",
    "  SELECT percentile INTO v_attempt.percentile",
    "  FROM public.test_attempts",
    "  WHERE id = v_attempt.id;",
    "",
    "  SELECT jsonb_build_object(",
    "    'id', p.id,",
    "    'full_name', p.full_name,",
    "    'email', p.email,",
    "    'role', p.role,",
    "    'batch_id', p.batch_id",
    "  )",
    "  INTO v_user",
    "  FROM public.profiles p",
    "  WHERE p.id = v_uid;",
    "",
    "  v_leaderboard_batch_id := CASE WHEN COALESCE(v_test.is_open_for_all, FALSE) = TRUE THEN NULL ELSE COALESCE(v_test.batch_id, v_profile.batch_id) END;",
    "",
    "  SELECT COALESCE(jsonb_agg(row_to_json(r)), '[]'::jsonb)",
    "  INTO v_leaderboard",
    "  FROM (",
    "    SELECT *",
    "    FROM public.test_attempt_summaries",
    "    WHERE test_id = p_test_id",
    "      AND (v_leaderboard_batch_id IS NULL OR batch_id = v_leaderboard_batch_id)",
    "    ORDER BY rank ASC, submitted_at ASC",
    "    LIMIT 20",
    "  ) r;",
    "",
    "  SELECT COALESCE(jsonb_agg(row_to_json(r)), '[]'::jsonb)",
    "  INTO v_overall_leaderboard",
    "  FROM (",
    "    SELECT *",
    "    FROM public.test_attempt_summaries",
    "    WHERE test_id = p_test_id",
    "    ORDER BY rank ASC, submitted_at ASC",
    "    LIMIT 20",
    "  ) r;",
    "",
    "  v_result := jsonb_build_object(",
    "    'id', v_attempt.id,",
    "    'attempt_id', v_attempt.id,",
    "    'result_id', v_attempt.id,",
    "    'test_id', v_attempt.test_id,",
    "    'user_id', v_attempt.user_id,",
    "    'student_name', v_final_student_name,",
    "    'score', v_attempt.score,",
    "    'correct_answers', v_attempt.correct_answers,",
    "    'wrong_answers', v_attempt.wrong_answers,",
    "    'unattempted', v_attempt.unattempted,",
    "    'total_questions', v_attempt.total_questions,",
    "    'percentile', v_attempt.percentile,",
    "    'submitted_at', v_attempt.submitted_at",
    "  );",
    "",
    "  RETURN jsonb_build_object(",
    "    'attempt', row_to_json(v_attempt),",
    "    'result', v_result,",
    "    'user', v_user,",
    "    'leaderboard', v_leaderboard,",
    "    'overall_leaderboard', v_overall_leaderboard",
    "  );",
    "END;",
    "$$;",
    "",
    "GRANT EXECUTE ON FUNCTION public.submit_test_attempt(UUID, JSONB, TEXT) TO authenticated;",
    "GRANT EXECUTE ON FUNCTION public.submit_test_attempt(UUID, JSONB, TEXT) TO anon;",
    "",
    "-- 2. Update list_test_questions to allow access for all students on Open for All tests",
    "CREATE OR REPLACE FUNCTION public.list_test_questions(p_test_id uuid)",
    "RETURNS TABLE (",
    "  id uuid,",
    "  test_id uuid,",
    "  question_type text,",
    "  prompt text,",
    "  options jsonb,",
    "  correct_answer text,",
    "  integer_answer integer,",
    "  explanation text,",
    "  image_url text,",
    "  subject_label text",
    ")",
    "LANGUAGE plpgsql",
    "SECURITY DEFINER",
    "SET search_path = public",
    "AS $$",
    "DECLARE",
    "  v_test public.tests;",
    "  v_profile public.profiles;",
    "BEGIN",
    "  IF auth.uid() IS NULL THEN",
    "    RAISE EXCEPTION 'Authentication required';",
    "  END IF;",
    "",
    "  SELECT * INTO v_profile FROM public.profiles WHERE id = auth.uid();",
    "",
    "  SELECT * INTO v_test FROM public.tests t WHERE t.id = p_test_id AND t.is_published = true AND t.deleted_at IS NULL;",
    "",
    "  IF v_test.id IS NULL THEN",
    "    RAISE EXCEPTION 'Test not found';",
    "  END IF;",
    "",
    "  IF v_test.type = 'scholarship' AND NOT public.is_admin() AND v_profile.role = 'miitjee_student' THEN",
    "    RAISE EXCEPTION 'MIITJEE students cannot open scholarship tests';",
    "  END IF;",
    "",
    "  IF NOT (",
    "    public.is_admin()",
    "    OR COALESCE(v_test.is_open_for_all, FALSE) = TRUE",
    "    OR v_test.batch_id IS NULL",
    "    OR v_test.batch_id = 'ALL'",
    "    OR LOWER(v_test.batch_id) = 'all batches'",
    "    OR v_test.type = 'scholarship'",
    "    OR EXISTS (",
    "      SELECT 1 FROM public.profiles p",
    "      WHERE p.id = auth.uid() AND p.batch_id IS NOT NULL AND p.batch_id = v_test.batch_id",
    "    )",
    "  ) THEN",
    "    RAISE EXCEPTION 'You are not eligible to view this test';",
    "  END IF;",
    "",
    "  RETURN QUERY",
    "  SELECT",
    "    q.id,",
    "    q.test_id,",
    "    q.question_type::text,",
    "    q.prompt,",
    "    q.options,",
    "    q.correct_answer,",
    "    q.integer_answer,",
    "    q.explanation,",
    "    q.image_url,",
    "    q.subject_label",
    "  FROM public.test_questions q",
    "  WHERE q.test_id = p_test_id",
    "  ORDER BY q.position ASC;",
    "END;",
    "$$;",
    "",
    "GRANT EXECUTE ON FUNCTION public.list_test_questions(uuid) TO authenticated;",
    "GRANT EXECUTE ON FUNCTION public.list_test_questions(uuid) TO anon;",
    "",
    "-- 3. Insert / Seed Navigator Batch MIITJEE Question Paper Test",
    "DELETE FROM public.tests WHERE id = 'a0000000-0000-0000-0000-000000000075';",
    "",
    "INSERT INTO public.tests (",
    "  id,",
    "  title,",
    "  description,",
    "  duration_minutes,",
    "  batch_id,",
    "  type,",
    "  subject,",
    "  scheduled_at,",
    "  is_published,",
    "  is_started,",
    "  started_at,",
    "  is_open_for_all",
    ") VALUES (",
    "  'a0000000-0000-0000-0000-000000000075',",
    "  'Navigator Batch MIITJEE Question Paper',",
    "  'Weekly Grand Test: Physics, Chemistry & Mathematics (75 Questions, 300 Marks). Open for all batches.',",
    "  180,",
    "  NULL,",
    "  'weekly',",
    "  'Physics, Chemistry, Mathematics',",
    "  timezone('utc', now()),",
    "  true,",
    "  true,",
    "  timezone('utc', now()),",
    "  true",
    ");",
    ""
]

# Add inserts for all questions
for q in cleaned_questions:
    prompt_escaped = q['prompt'].replace("'", "''")
    exp_escaped = q['explanation'].replace("'", "''")
    sub_escaped = q['subject_label'].replace("'", "''")
    opts_json = json.dumps(q['options'], ensure_ascii=False).replace("'", "''")
    ans_escaped = q['correct_answer'].replace("'", "''")
    int_ans_str = str(q['integer_answer']) if q['integer_answer'] is not None else 'NULL'
    img_val = f"'{q['image_url']}'" if q['image_url'] else 'NULL'
    
    sql_lines.append(f"""INSERT INTO public.test_questions (
  test_id, position, question_type, prompt, options, correct_answer, integer_answer, explanation, image_url, subject_label
) VALUES (
  'a0000000-0000-0000-0000-000000000075',
  {q['position']},
  '{q['question_type']}',
  '{prompt_escaped}',
  '{opts_json}'::jsonb,
  '{ans_escaped}',
  {int_ans_str},
  '{exp_escaped}',
  {img_val},
  '{sub_escaped}'
);""")

out_sql_path = r'D:\Downloads\miitjee-mobile\supabase\migrations\20260906010000_navigator_batch_test_and_submission_fix.sql'
with open(out_sql_path, 'w', encoding='utf-8') as sql_f:
    sql_f.write('\n'.join(sql_lines) + '\n')

print(f"Generated SQL migration file: {out_sql_path} ({len(sql_lines)} lines)")
